gradle task to create docker file, register docker image to bmuschko api

diff --git a/Database/build/scripts/Database b/Database/build/scripts/Database
--- a/Database/build/scripts/Database
+++ b/Database/build/scripts/Database
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 #
-# Copyright © 2015-2021 the original authors.
+# Copyright Â© 2015-2021 the original authors.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -32,10 +32,10 @@
 #       Busybox and similar reduced shells will NOT work, because this script
 #       requires all of these POSIX shell features:
 #         * functions;
-#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
-#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
-#         * compound commands having a testable exit status, especially «case»;
-#         * various built-in commands including «command», «set», and «ulimit».
+#         * expansions Â«$varÂ», Â«${var}Â», Â«${var:-default}Â», Â«${var+SET}Â»,
+#           Â«${var#prefix}Â», Â«${var%suffix}Â», and Â«$( cmd )Â»;
+#         * compound commands having a testable exit status, especially Â«caseÂ»;
+#         * various built-in commands including Â«commandÂ», Â«setÂ», and Â«ulimitÂ».
 #
 #   Important for patching:
 #
@@ -114,9 +114,9 @@ case "$( uname )" in                #(
   NONSTOP* )        nonstop=true ;;
 esac
 
-CLASSPATH=$APP_HOME/lib/mysql-connector-java-8.0.29.jar
+CLASSPATH="\\\"\\\""
 
-MODULE_PATH=$APP_HOME/lib/Database-1.0-SNAPSHOT-plain.jar:$APP_HOME/lib/HikariCP-5.0.1.jar:$APP_HOME/lib/utilities-1.0-SNAPSHOT.jar:$APP_HOME/lib/jooq-meta-3.16.6.jar:$APP_HOME/lib/jooq-3.16.6.jar:$APP_HOME/lib/slf4j-api-1.7.30.jar:$APP_HOME/lib/list-1.0-SNAPSHOT.jar:$APP_HOME/lib/r2dbc-spi-0.9.0.RELEASE.jar:$APP_HOME/lib/jakarta.xml.bind-api-3.0.0.jar:$APP_HOME/lib/protobuf-java-3.19.4.jar:$APP_HOME/lib/reactive-streams-1.0.3.jar:$APP_HOME/lib/jakarta.activation-2.0.0.jar
+MODULE_PATH=$APP_HOME/lib/Database-1.0-SNAPSHOT.jar:$APP_HOME/lib/utilities-1.0-SNAPSHOT.jar:$APP_HOME/lib/list-1.0-SNAPSHOT.jar
 
 
 # Determine the Java command to use to start the JVM.
@@ -204,8 +204,14 @@ fi
 set -- \
         -classpath "$CLASSPATH" \
         --module-path "$MODULE_PATH" \
-        --module com.example.Database/com.example.database.Application \
+        --module com.example.Database \
         "$@"
+
+# Stop when "xargs" is not available.
+if ! command -v xargs >/dev/null 2>&1
+then
+    die "xargs is not available"
+fi
 
 # Use "xargs" to parse quoted args.
 #
